repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.54.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-mocha@10.2.0
          - eslint-plugin-prettier@5.0.1
          - prettier@3.1.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [css, javascript]
